//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanArchiving
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveInfo
    {
        public int ID { get; set; }
        public string 编号 { get; set; }
        public string 图名 { get; set; }
        public string 图号 { get; set; }
        public Nullable<int> 是否归档 { get; set; }
        public string pdf { get; set; }
        public string dwf { get; set; }
        public string plt { get; set; }
        public string dwg { get; set; }
        public string Attachment { get; set; }
        public int Sort { get; set; }
        public string FileName { get; set; }
    }
}
