//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanArchiving
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string TypeCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public string DesignUnit { get; set; }
        public Nullable<int> RoadLevel { get; set; }
        public Nullable<double> RoadHeight { get; set; }
        public Nullable<double> PlanningMileage { get; set; }
        public Nullable<double> DesignMileage { get; set; }
        public Nullable<double> PreMileage { get; set; }
        public Nullable<double> DrawingDesignMileage { get; set; }
        public Nullable<double> WorkingMileage { get; set; }
        public Nullable<double> Investment { get; set; }
        public string Awards { get; set; }
        public string Remarks { get; set; }
        public bool IsDelete { get; set; }
        public int Sort { get; set; }
    }
}
