//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanArchiving
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume
    {
        public System.Guid VolumeID { get; set; }
        public System.Guid ProjectID { get; set; }
        public string Keyword { get; set; }
        public string ArchiveCode { get; set; }
        public string VolumeCode { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string TypeCode { get; set; }
        public string DossierCode { get; set; }
        public string TemporaryCode { get; set; }
        public string VolumeName { get; set; }
        public string VolumeText { get; set; }
        public string VolumeTitle { get; set; }
        public Nullable<int> ArchiveNumber { get; set; }
        public string VolumeLocation { get; set; }
        public Nullable<System.DateTime> OrganizationDate { get; set; }
        public string OrganizationUnit { get; set; }
        public string Phase { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string Themewords { get; set; }
        public string KeepDate { get; set; }
        public string SecretLevel { get; set; }
        public Nullable<System.DateTime> IdentifyDate { get; set; }
        public string SerialNumber { get; set; }
        public string Symbol { get; set; }
        public string Responsibler { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public string Remarks { get; set; }
        public bool IsDelete { get; set; }
        public int Sort { get; set; }
    }
}
